#%RAML 0.8
title: moyd.co DNS
version: v1
baseUri: https://api.domain.tld/{version}
schemas:    
  - region: !include region    
  - neighbor_region: !include neighbor_region
  - api_account: !include api_account 
  - check: !include check
  - record: !include record
  - domain: !include domain
  - user: !include user
/dns_datas:
  /check_list:
    get:
      description: Get all checks configured
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "reference":"check_id_1",
                    "ip_address":"192.168.0.1",
                    "check":"check_ping",
                    "check_args":"-w 10 -c 20",
                    "enabled":"true"
                  },
                  {
                    "reference":"check_id_2",
                    "ip_address":"192.168.0.2",
                    "check":"check_http",
                    "check_args":"",
                    "enabled":"true"
                  }
                ]
  /query_count:
    post:
      description: Update the number of queries for a domain
      queryParameters:
        query:
          type: string
          description: a JSON with the region name id and all domain queries details
          example: |
            {
              "region":'121123a1d1e1",
              "queryCount":
              {
                "domain1.tld":12,
                "domain2.tld":32
              }
            }
      responses:
        200:
          description: If all was OK
  /update_from_check:
    /{id}:
      post:
        description: Update check status and linked records
        queryParameters:
          id: 
            type: string
            description: check id
          status:
            type: string
            description: The new status
            example: OK | WARNING | UNKNOWN | CRITICAL
        responses:
          200:
            description: If all was OK
  get:
    description: Get all zone names
    responses:
      200:
        description: All zone names on one line separated by space
        body:
          application/json:
            example: |
              domain1.tld domain2.tld    
  /{id}:
    get:
      description: Get the json describing the zone
      queryParameters:
        id: 
          description: zone ID
/regions:
  /{region_id}:
    get:
      description: Return a region 
      responses:
        200:
          description: A json with a region description
          body:
            application/json:
              schema: region
              example: |
                {
                  "_id":{"$oid":"ffedca8c0000eff666eeb35d"},
                  "check_ip_address":null,
                  "code":"ve.it",
                  "country_code":null,
                  "dns_ip_address":"192.168.1.130",
                  "has_check":false,
                  "has_dns":true
                }
    put:
      description: Update a region
      queryParameters:
        region:
          description: A json with all details
          example: |
           {
              "check_ip_address":null,
              "code":"pd.it",
              "country_code":null,
              "dns_ip_address":"192.168.3.10",
              "has_check":false,
              "has_dns":true
            }
      responses:
        200:
          description: a json which describe updated region
          body: 
            application/json:
              schema: region
              example: |
               {
                  "check_ip_address":null,
                  "code":"pd.it",
                  "country_code":null,
                  "dns_ip_address":"192.168.3.10",
                  "has_check":false,
                  "has_dns":true
                }
        404:
          description: Error
    delete:
      description: Destroy a region
      responses:
        200:
          description: a json which describe deleted region
          body: 
            application/json:
              schema: region
              example: |
               {
                  "check_ip_address":null,
                  "code":"pd.it",
                  "country_code":null,
                  "dns_ip_address":"192.168.3.10",
                  "has_check":false,
                  "has_dns":true
                }
        404:
          description: Error
    /dns_server_statuses:
      get:
        description: <<insert text or markdown here>>
      post:
        description: <<insert text or markdown here>>
    /dns_server_logs:
      get:
        description: <<insert text or markdown here>>
      post:
        description: <<insert text or markdown here>>
    /neighbors:
      get:
        description: Return all regions neighbor of selected region
        responses:
          200:
            description: a json whith all neighbor of a region
            body: 
              application/json:
                schema: neighbor_region
      post:
        description: Add a neighbor
        queryParameters:
          neighbor:
            description: A json with the id of the new neighbor and the proximity
            example: |
             {
                "neighbor_region":"1982812af21ab",
                "proximity":10
              }
        responses:
          200:
            description: a json whith all neighbor of a region
            body: 
              application/json:
                schema: neighbor_region
      /{id}:
        get:
          description: Return a neighbor of selected region
          responses:
            200:
              description: a json whith the neighbor
              body: 
                application/json:
                  schema: neighbor_region
        put:
          description: Update a neighbor
          queryParameters:
            neighbor:
              description: A json with the id of the new neighbor and the proximity
              example: |
               {
                  "neighbor_region":"1982812af21ab",
                  "proximity":10
                }
          responses:
            200:
              description: a json whith the neighbor
              body: 
                application/json:
                  schema: neighbor_region
        delete:
          description: Delete a neighbor
          responses:
            200:
              description: a json whith deleted neighbor
              body: 
                application/json:
                  schema: neighbor_region
  get:
    description: Return all regions   
    responses:
      200:
        description: A json with all regions
        body:
          application/json:
            schema: region
            example: |
              [
                {
                  "_id":{"$oid":"ffedca8c0000eff666eeb35d"},
                  "check_ip_address":null,
                  "code":"ve.it",
                  "country_code":null,
                  "dns_ip_address":"192.168.1.130",
                  "has_check":false,
                  "has_dns":true},
                {
                  "_id":{"$oid":"001ed4f60000ecfa2412a846"},
                  "check_ip_address":null,
                  "code":"pd.it",
                  "country_code":null,
                  "dns_ip_address":"192.168.3.10",
                  "has_check":false,
                  "has_dns":true
                }
              ]
  post:
    description: Create a region
    queryParameters:
      region:
        description: A json with all details
        example: |
         {
            "check_ip_address":null,
            "code":"pd.it",
            "country_code":null,
            "dns_ip_address":"192.168.3.10",
            "has_check":false,
            "has_dns":true
          }
    responses:
      200:
        description: a json which describe created region
        body: 
          application/json:
            schema: region
            example: |
             {
                "check_ip_address":null,
                "code":"pd.it",
                "country_code":null,
                "dns_ip_address":"192.168.3.10",
                "has_check":false,
                "has_dns":true
              }
      404:
        description: Error
/users:
  /{user_id}:
    /api_accounts:
      get:
        description: Return all api accounts owned by User
        responses:
          200:
            description: a json with all api accounts
            body: 
              application/json:
                schema: api_account
                example: |
                 [{
                   "_id":{"$oid":"542be0dced44ecea70000003"},
                   "api_secret":"29U3kG7rLxG3uTopjCueB9lTxyifmtI20k4mg5YZLOX3GDujeW7I8lgNI8bm2JxF",
                   "rights":["check"],
                   "user_id":{"$oid":"000ab90d0000f2b7219ea5d7"}
                  },
                  {
                   "_id":{"$oid":"542be0dced44ecea70000004"},
                   "api_secret":"29U3kG7rLxG3uTopjCueB9lTxyifmtI20k4mg5YZLOX3GDujeW7I8lgNI8424xF",
                   "rights":["domain","record"],
                   "user_id":{"$oid":"000ab90d0000f2b7219ea5d7"}
                  }
                  ]
          404:
            description: Error
      post:
        description: Create a new api accounts for the User
        queryParameters:
          api_account:
            description: A json with all details
            example: |
             {
                "rights":["domain","record"]
              }
        responses:
          200:
            description: a json with the new api accounts
            body: 
              application/json:
                schema: api_account
                example: |
                 {
                   "_id":{"$oid":"542be0dced44ecea70000003"},
                   "api_secret":"29U3kG7rLxG3uTopjCueB9lTxyifmtI20k4mg5YZLOX3GDujeW7I8lgNI8bm2JxF",
                   "rights":["check"],
                   "user_id":{"$oid":"000ab90d0000f2b7219ea5d7"}
                  }
          404:
            description: Error
      /{id}:
        get:
          description: Get an api accounts for the User
          responses:
            200:
              description: a json with the api accounts
              body: 
                application/json:
                  schema: api_account
                  example: |
                   {
                     "_id":{"$oid":"542be0dced44ecea70000003"},
                     "api_secret":"29U3kG7rLxG3uTopjCueB9lTxyifmtI20k4mg5YZLOX3GDujeW7I8lgNI8bm2JxF",
                     "rights":["check"],
                     "user_id":{"$oid":"000ab90d0000f2b7219ea5d7"}
                    }
            404:
              description: Error
        put:
          description: Edit an api accounts for the User
          queryParameters:
            api_account:
              description: A json with all details
              example: |
               {
                  "rights":["domain","record"]
                }
          responses:
            200:
              description: a json with the updated api accounts
              body: 
                application/json:
                  schema: api_account
                  example: |
                   {
                     "_id":{"$oid":"542be0dced44ecea70000003"},
                     "api_secret":"29U3kG7rLxG3uTopjCueB9lTxyifmtI20k4mg5YZLOX3GDujeW7I8lgNI8bm2JxF",
                     "rights":["check"],
                     "user_id":{"$oid":"000ab90d0000f2b7219ea5d7"}
                    }
            404:
              description: Error
        delete:
          description: Delete an api accounts for the User
          responses:
            200:
              description: a json with the deleted api accounts
              body: 
                application/json:
                  schema: api_account
                  example: |
                   {
                     "_id":{"$oid":"542be0dced44ecea70000003"},
                     "api_secret":"29U3kG7rLxG3uTopjCueB9lTxyifmtI20k4mg5YZLOX3GDujeW7I8lgNI8bm2JxF",
                     "rights":["check"],
                     "user_id":{"$oid":"000ab90d0000f2b7219ea5d7"}
                    }
            404:
              description: Error
    /checks:
      /{id}:
        get:
          description: Get a checks
          responses:
            200:
              description: a json with the check
              body: 
                application/json:
                  schema: check
                  example: |
                    {
                      "_id\":{"$oid":"542be0dced44ecea70000002"},
                      "admin_enabled":true,
                      "check":"PASSIVE",
                      "check_args":null,
                      "created_at":"2014-10-01T11:09:16.510Z",
                      "enabled":true,
                      "hard_count":999,
                      "hard_status":true,
                      "ip":null,
                      "last_bill":"2014-10-01",
                      "name":null,
                      "reports_only":false,
                      "soft_count":0,
                      "soft_status":true,
                      "soft_to_hard_to_disable":3,
                      "soft_to_hard_to_enable":3,
                      "updated_at":"2014-10-01T11:09:16.510Z",
                      "user_id":{"$oid":"000ab90d0000f2b7219ea5d7"}
                    }
            404:
              description: Error
        put:
          description: Update a check
          queryParameters:
            check:
              description: A json with all details
              example: |
               {
                  "name":null,
                  "ip":null,
                  "check":"PASSIVE",
                  "check_args":null,
                  "soft_to_hard_to_disable":3,
                  "soft_to_hard_to_enable":3,
                }
          responses:
            200:
              description: a json with the updated checks
              body: 
                application/json:
                  schema: check
                  example: |
                    {
                      "_id\":{"$oid":"542be0dced44ecea70000002"},
                      "admin_enabled":true,
                      "check":"PASSIVE",
                      "check_args":null,
                      "created_at":"2014-10-01T11:09:16.510Z",
                      "enabled":true,
                      "hard_count":999,
                      "hard_status":true,
                      "ip":null,
                      "last_bill":"2014-10-01",
                      "name":null,
                      "reports_only":false,
                      "soft_count":0,
                      "soft_status":true,
                      "soft_to_hard_to_disable":3,
                      "soft_to_hard_to_enable":3,
                      "updated_at":"2014-10-01T11:09:16.510Z",
                      "user_id":{"$oid":"000ab90d0000f2b7219ea5d7"}
                    }
            404:
              description: Error
        delete:
          description: Delete a checks
          responses:
            200:
              description: a json with the deleted check
              body: 
                application/json:
                  schema: check
                  example: |
                    {
                      "_id\":{"$oid":"542be0dced44ecea70000002"},
                      "admin_enabled":true,
                      "check":"PASSIVE",
                      "check_args":null,
                      "created_at":"2014-10-01T11:09:16.510Z",
                      "enabled":true,
                      "hard_count":999,
                      "hard_status":true,
                      "ip":null,
                      "last_bill":"2014-10-01",
                      "name":null,
                      "reports_only":false,
                      "soft_count":0,
                      "soft_status":true,
                      "soft_to_hard_to_disable":3,
                      "soft_to_hard_to_enable":3,
                      "updated_at":"2014-10-01T11:09:16.510Z",
                      "user_id":{"$oid":"000ab90d0000f2b7219ea5d7"}
                    }
            404:
              description: Error
        /show_records:
          get:
            description: Show the records for a check
            responses:
              200:
                description: a json with all records
                body: 
                  application/json:
                    schema: records
                    example: |
                     [
                     {
                       "_id":{"$oid":"ffe6eba40000315f33abb8cc"},
                       "alias":false,
                       "answers":
                         [{
                           "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                           "algorithm":5,
                           "at":"60",
                           "data":null,
                           "expire":"1M",
                           "flags":null,
                           "ip":null,
                           "keyTag":null,
                           "labels":3,
                           "minimum":"1M",
                           "mname":"ns01.moyd.co.",
                           "originalTTL":null,
                           "port":80,
                           "priority":10,
                           "protocol":null,
                           "publicKey":null,
                           "refresh":"1M",
                           "retry":"1M",
                           "rname":"domains@moyd.co",
                           "serial":1409220000,
                           "signature":null,
                           "signatureExpiration":null,
                           "signatureInception":null,
                           "signerName":null,
                           "typeCovered":1,
                           "weight\":1}],
                         "check_id":null,
                         "created_at":"2014-09-22T15:43:47.846Z",
                         "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                         "enabled":true,
                         "name":"",
                         "operational":true,
                         "primary":true,
                         "region_id":null,
                         "routing_policy":"SIMPLE",
                         "set_id":null,
                         "trashed":false,
                         "ttl":60,
                         "type":"SOA",
                         "updated_at":"2014-09-22T15:43:47.846Z",
                         "version":0,
                         "weight\":1
                      },
                      {
                       "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                       "alias":false,
                       "answers":
                         [{
                           "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                           "algorithm":5,
                           "at":"60",
                           "data":null,
                           "expire":"1M",
                           "flags":null,
                           "ip":null,
                           "keyTag":null,
                           "labels":3,
                           "minimum":"1M",
                           "mname":"ns01.moyd.co.",
                           "originalTTL":null,
                           "port":80,
                           "priority":10,
                           "protocol":null,
                           "publicKey":null,
                           "refresh":"1M",
                           "retry":"1M",
                           "rname":"domains@moyd.co",
                           "serial":1409220000,
                           "signature":null,
                           "signatureExpiration":null,
                           "signatureInception":null,
                           "signerName":null,
                           "typeCovered":1,
                           "weight\":1}],
                         "check_id":null,
                         "created_at":"2014-09-22T15:43:47.846Z",
                         "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                         "enabled":true,
                         "name":"www",
                         "operational":true,
                         "primary":true,
                         "region_id":null,
                         "routing_policy":"SIMPLE",
                         "set_id":null,
                         "trashed":false,
                         "ttl":60,
                         "type":"SOA",
                         "updated_at":"2014-09-22T15:43:47.846Z",
                         "version":0,
                         "weight\":1
                      },
                      ]
              404:
                description: Error
        /passive_update:
          put:
            description: Update a passive check status
            queryParameters:
              status:
                description: the new status
                example: OK | WARNING | UNKNOWN | CRITICAL
            responses:
              200:
                description: a json with the updated checks
                body: 
                  application/json:
                    schema: check
                    example: |
                      {
                        "_id\":{"$oid":"542be0dced44ecea70000002"},
                        "admin_enabled":true,
                        "check":"PASSIVE",
                        "check_args":null,
                        "created_at":"2014-10-01T11:09:16.510Z",
                        "enabled":true,
                        "hard_count":999,
                        "hard_status":true,
                        "ip":null,
                        "last_bill":"2014-10-01",
                        "name":null,
                        "reports_only":false,
                        "soft_count":0,
                        "soft_status":true,
                        "soft_to_hard_to_disable":3,
                        "soft_to_hard_to_enable":3,
                        "updated_at":"2014-10-01T11:09:16.510Z",
                        "user_id":{"$oid":"000ab90d0000f2b7219ea5d7"}
                      }
              404:
                description: Error
        /show_url:
          get:
            description: Show the url for a passive check
            responses:
              200:
                description: a json with the url description
                body: 
                  application/json:
                    schema: check
                    example: |
                      {
                      base_uri: "https://api.moyd.co",
                      uri: "/v1/users/12321ab524a23ae12/checks/12321ab524a23123/passive_update",
                      method: 'PUT',
                      api_key: 'api_key',
                      api_secret: 'api_secret',
                      soft_to_hard_to_disable: 10,
                      soft_to_hard_to_enable: 12
                      }
    get:
      description: Return all checks owned by User
      responses:
        200:
          description: a json with all checks
          body: 
            application/json:
              schema: check
              example: |
               [
               {
                  "_id":{"$oid":"ffe6c2a60000798c62599730"},
                  "admin_enabled":true,
                  "check":"check_ping",
                  "check_args":null,
                  "created_at":"2014-09-22T12:48:54.218Z",
                  "enabled":true,
                  "hard_count":999,
                  "hard_status":true,
                  "ip":"127.0.0.1",
                  "last_bill":"2014-09-22",
                  "name":"pippo",
                  "reports_only":false,
                  "soft_count":0,
                  "soft_status":true,
                  "soft_to_hard_to_disable":3,
                  "soft_to_hard_to_enable":3,
                  "updated_at":"2014-09-22T14:59:18.943Z",
                  "user_id":{"$oid\":"ffe1817f0000f5ae959ec2a7"}
                },
                {
                  "_id\":{"$oid":"542be0dced44ecea70000002"},
                  "admin_enabled":true,
                  "check":"PASSIVE",
                  "check_args":null,
                  "created_at":"2014-10-01T11:09:16.510Z",
                  "enabled":true,
                  "hard_count":999,
                  "hard_status":true,
                  "ip":null,
                  "last_bill":"2014-10-01",
                  "name":null,
                  "reports_only":false,
                  "soft_count":0,
                  "soft_status":true,
                  "soft_to_hard_to_disable":3,
                  "soft_to_hard_to_enable":3,
                  "updated_at":"2014-10-01T11:09:16.510Z",
                  "user_id":{"$oid":"000ab90d0000f2b7219ea5d7"}
                }
                ]
        404:
          description: Error
    post:
      description: Add a check
      queryParameters:
        check:
          description: A json with all details
          example: |
           {
              "name":null,
              "ip":null,
              "check":"PASSIVE",
              "check_args":null,
              "soft_to_hard_to_disable":3,
              "soft_to_hard_to_enable":3,
            }
      responses:
        200:
          description: a json with the new checks
          body: 
            application/json:
              schema: check
              example: |
                {
                  "_id\":{"$oid":"542be0dced44ecea70000002"},
                  "admin_enabled":true,
                  "check":"PASSIVE",
                  "check_args":null,
                  "created_at":"2014-10-01T11:09:16.510Z",
                  "enabled":true,
                  "hard_count":999,
                  "hard_status":true,
                  "ip":null,
                  "last_bill":"2014-10-01",
                  "name":null,
                  "reports_only":false,
                  "soft_count":0,
                  "soft_status":true,
                  "soft_to_hard_to_disable":3,
                  "soft_to_hard_to_enable":3,
                  "updated_at":"2014-10-01T11:09:16.510Z",
                  "user_id":{"$oid":"000ab90d0000f2b7219ea5d7"}
                }
        404:
          description: Error
    /domains:
      /{domain_id}:
        /records:
          get:
            description: Return all records of a domain
            responses:
              200:
                description: a json with all records
                body: 
                  application/json:
                    schema: records
                    example: |
                     [
                     {
                       "_id":{"$oid":"ffe6eba40000315f33abb8cc"},
                       "alias":false,
                       "answers":
                         [{
                           "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                           "algorithm":5,
                           "at":"60",
                           "data":null,
                           "expire":"1M",
                           "flags":null,
                           "ip":null,
                           "keyTag":null,
                           "labels":3,
                           "minimum":"1M",
                           "mname":"ns01.moyd.co.",
                           "originalTTL":null,
                           "port":80,
                           "priority":10,
                           "protocol":null,
                           "publicKey":null,
                           "refresh":"1M",
                           "retry":"1M",
                           "rname":"domains@moyd.co",
                           "serial":1409220000,
                           "signature":null,
                           "signatureExpiration":null,
                           "signatureInception":null,
                           "signerName":null,
                           "typeCovered":1,
                           "weight\":1}],
                         "check_id":null,
                         "created_at":"2014-09-22T15:43:47.846Z",
                         "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                         "enabled":true,
                         "name":"",
                         "operational":true,
                         "primary":true,
                         "region_id":null,
                         "routing_policy":"SIMPLE",
                         "set_id":null,
                         "trashed":false,
                         "ttl":60,
                         "type":"SOA",
                         "updated_at":"2014-09-22T15:43:47.846Z",
                         "version":0,
                         "weight\":1
                      },
                      {
                       "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                       "alias":false,
                       "answers":
                         [{
                           "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                           "algorithm":5,
                           "at":"60",
                           "data":null,
                           "expire":"1M",
                           "flags":null,
                           "ip":null,
                           "keyTag":null,
                           "labels":3,
                           "minimum":"1M",
                           "mname":"ns01.moyd.co.",
                           "originalTTL":null,
                           "port":80,
                           "priority":10,
                           "protocol":null,
                           "publicKey":null,
                           "refresh":"1M",
                           "retry":"1M",
                           "rname":"domains@moyd.co",
                           "serial":1409220000,
                           "signature":null,
                           "signatureExpiration":null,
                           "signatureInception":null,
                           "signerName":null,
                           "typeCovered":1,
                           "weight\":1}],
                         "check_id":null,
                         "created_at":"2014-09-22T15:43:47.846Z",
                         "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                         "enabled":true,
                         "name":"www",
                         "operational":true,
                         "primary":true,
                         "region_id":null,
                         "routing_policy":"SIMPLE",
                         "set_id":null,
                         "trashed":false,
                         "ttl":60,
                         "type":"SOA",
                         "updated_at":"2014-09-22T15:43:47.846Z",
                         "version":0,
                         "weight":1
                      },
                      ]
              404:
                description: Error
          post:
            description: Add a record
            queryParameters:
              record:
                description: A json with all details
                example: |
                 {
                   "alias":false,
                   "answer_attributes":
                     [{
                       "algorithm":5,
                       "at":"60",
                       "data":null,
                       "expire":"1M",
                       "flags":null,
                       "ip":null,
                       "keyTag":null,
                       "labels":3,
                       "minimum":"1M",
                       "mname":"ns01.moyd.co.",
                       "originalTTL":null,
                       "port":80,
                       "priority":10,
                       "protocol":null,
                       "publicKey":null,
                       "refresh":"1M",
                       "retry":"1M",
                       "rname":"domains@moyd.co",
                       "signature":null,
                       "signatureExpiration":null,
                       "signatureInception":null,
                       "signerName":null,
                       "typeCovered":1,
                       "weight\":1}],
                     "enabled":true,
                     "name":"www",
                     "primary":true,
                     "routing_policy":"SIMPLE",
                     "set_id":null,
                     "ttl":60,
                     "type":"SOA",
                     "weight":1
                  }
            responses:
              200:
                description: a json with the added records
                body: 
                  application/json:
                    schema: records
                    example: |
                      {
                       "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                       "alias":false,
                       "answers":
                         [{
                           "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                           "algorithm":5,
                           "at":"60",
                           "data":null,
                           "expire":"1M",
                           "flags":null,
                           "ip":null,
                           "keyTag":null,
                           "labels":3,
                           "minimum":"1M",
                           "mname":"ns01.moyd.co.",
                           "originalTTL":null,
                           "port":80,
                           "priority":10,
                           "protocol":null,
                           "publicKey":null,
                           "refresh":"1M",
                           "retry":"1M",
                           "rname":"domains@moyd.co",
                           "serial":1409220000,
                           "signature":null,
                           "signatureExpiration":null,
                           "signatureInception":null,
                           "signerName":null,
                           "typeCovered":1,
                           "weight\":1}],
                         "check_id":null,
                         "created_at":"2014-09-22T15:43:47.846Z",
                         "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                         "enabled":true,
                         "name":"www",
                         "operational":true,
                         "primary":true,
                         "region_id":null,
                         "routing_policy":"SIMPLE",
                         "set_id":null,
                         "trashed":false,
                         "ttl":60,
                         "type":"SOA",
                         "updated_at":"2014-09-22T15:43:47.846Z",
                         "version":0,
                         "weight\":1
                      }
              404:
                description: Error
          /empty_trash:
            post:
              description: Destroy all trashed records
              responses:
                200:
                  description: a json with all records trashed
                  body: 
                    application/json:
                      schema: records
                      example: |
                       [
                       {
                         "_id":{"$oid":"ffe6eba40000315f33abb8cc"},
                         "alias":false,
                         "answers":
                           [{
                             "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                             "algorithm":5,
                             "at":"60",
                             "data":null,
                             "expire":"1M",
                             "flags":null,
                             "ip":null,
                             "keyTag":null,
                             "labels":3,
                             "minimum":"1M",
                             "mname":"ns01.moyd.co.",
                             "originalTTL":null,
                             "port":80,
                             "priority":10,
                             "protocol":null,
                             "publicKey":null,
                             "refresh":"1M",
                             "retry":"1M",
                             "rname":"domains@moyd.co",
                             "serial":1409220000,
                             "signature":null,
                             "signatureExpiration":null,
                             "signatureInception":null,
                             "signerName":null,
                             "typeCovered":1,
                             "weight\":1}],
                           "check_id":null,
                           "created_at":"2014-09-22T15:43:47.846Z",
                           "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                           "enabled":true,
                           "name":"",
                           "operational":true,
                           "primary":true,
                           "region_id":null,
                           "routing_policy":"SIMPLE",
                           "set_id":null,
                           "trashed":false,
                           "ttl":60,
                           "type":"SOA",
                           "updated_at":"2014-09-22T15:43:47.846Z",
                           "version":0,
                           "weight\":1
                        },
                        {
                         "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                         "alias":false,
                         "answers":
                           [{
                             "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                             "algorithm":5,
                             "at":"60",
                             "data":null,
                             "expire":"1M",
                             "flags":null,
                             "ip":null,
                             "keyTag":null,
                             "labels":3,
                             "minimum":"1M",
                             "mname":"ns01.moyd.co.",
                             "originalTTL":null,
                             "port":80,
                             "priority":10,
                             "protocol":null,
                             "publicKey":null,
                             "refresh":"1M",
                             "retry":"1M",
                             "rname":"domains@moyd.co",
                             "serial":1409220000,
                             "signature":null,
                             "signatureExpiration":null,
                             "signatureInception":null,
                             "signerName":null,
                             "typeCovered":1,
                             "weight\":1}],
                           "check_id":null,
                           "created_at":"2014-09-22T15:43:47.846Z",
                           "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                           "enabled":true,
                           "name":"www",
                           "operational":true,
                           "primary":true,
                           "region_id":null,
                           "routing_policy":"SIMPLE",
                           "set_id":null,
                           "trashed":false,
                           "ttl":60,
                           "type":"SOA",
                           "updated_at":"2014-09-22T15:43:47.846Z",
                           "version":0,
                           "weight":1
                        },
                        ]
                404:
                  description: Error
          /{id}:
            /update_link:
              put:
                description: Update the record linked with the service
                queryParameters:
                  check_id:
                    description: The ID of the linked check 
                responses:
                  200:
                    description: a json with the updated records
                    body: 
                      application/json:
                        schema: records
                        example: |
                          {
                           "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                           "alias":false,
                           "answers":
                             [{
                               "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                               "algorithm":5,
                               "at":"60",
                               "data":null,
                               "expire":"1M",
                               "flags":null,
                               "ip":null,
                               "keyTag":null,
                               "labels":3,
                               "minimum":"1M",
                               "mname":"ns01.moyd.co.",
                               "originalTTL":null,
                               "port":80,
                               "priority":10,
                               "protocol":null,
                               "publicKey":null,
                               "refresh":"1M",
                               "retry":"1M",
                               "rname":"domains@moyd.co",
                               "serial":1409220000,
                               "signature":null,
                               "signatureExpiration":null,
                               "signatureInception":null,
                               "signerName":null,
                               "typeCovered":1,
                               "weight\":1}],
                             "check_id":null,
                             "created_at":"2014-09-22T15:43:47.846Z",
                             "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                             "enabled":true,
                             "name":"www",
                             "operational":true,
                             "primary":true,
                             "region_id":null,
                             "routing_policy":"SIMPLE",
                             "set_id":null,
                             "trashed":false,
                             "ttl":60,
                             "type":"SOA",
                             "updated_at":"2014-09-22T15:43:47.846Z",
                             "version":0,
                             "weight\":1
                          }
                  404:
                    description: Error
            /old_versions:
              get:
                description: Get the old versions of a record
                responses:
                  200:
                    description: a json with the old records
                    body: 
                      application/json:
                        schema: records
                        example: |
                          [{
                           "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                           "alias":false,
                           "answers":
                             [{
                               "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                               "algorithm":5,
                               "at":"60",
                               "data":null,
                               "expire":"1M",
                               "flags":null,
                               "ip":null,
                               "keyTag":null,
                               "labels":3,
                               "minimum":"1M",
                               "mname":"ns01.moyd.co.",
                               "originalTTL":null,
                               "port":80,
                               "priority":10,
                               "protocol":null,
                               "publicKey":null,
                               "refresh":"1M",
                               "retry":"1M",
                               "rname":"domains@moyd.co",
                               "serial":1409220000,
                               "signature":null,
                               "signatureExpiration":null,
                               "signatureInception":null,
                               "signerName":null,
                               "typeCovered":1,
                               "weight\":1}],
                             "check_id":null,
                             "created_at":"2014-09-22T15:43:47.846Z",
                             "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                             "enabled":true,
                             "name":"www",
                             "operational":true,
                             "primary":true,
                             "region_id":null,
                             "routing_policy":"SIMPLE",
                             "set_id":null,
                             "trashed":false,
                             "ttl":60,
                             "type":"SOA",
                             "updated_at":"2014-09-22T15:43:47.846Z",
                             "version":0,
                             "weight\":1
                          },
                          {
                           "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                           "alias":false,
                           "answers":
                             [{
                               "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                               "algorithm":5,
                               "at":"60",
                               "data":null,
                               "expire":"1M",
                               "flags":null,
                               "ip":null,
                               "keyTag":null,
                               "labels":3,
                               "minimum":"1M",
                               "mname":"ns01.moyd.co.",
                               "originalTTL":null,
                               "port":80,
                               "priority":10,
                               "protocol":null,
                               "publicKey":null,
                               "refresh":"1M",
                               "retry":"1M",
                               "rname":"domains@moyd.co",
                               "serial":1409220000,
                               "signature":null,
                               "signatureExpiration":null,
                               "signatureInception":null,
                               "signerName":null,
                               "typeCovered":1,
                               "weight\":1}],
                             "check_id":null,
                             "created_at":"2014-09-22T15:43:47.846Z",
                             "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                             "enabled":true,
                             "name":"www",
                             "operational":true,
                             "primary":true,
                             "region_id":null,
                             "routing_policy":"SIMPLE",
                             "set_id":null,
                             "trashed":false,
                             "ttl":60,
                             "type":"SOA",
                             "updated_at":"2014-09-22T15:43:47.846Z",
                             "version":0,
                             "weight\":1
                          }]
                  404:
                    description: Error
            /redo_version:
              put:
                description: Redo an old record version
                queryParameters:
                  redo_id:
                    description: The ID of the old version 
                responses:
                  200:
                    description: a json with the updated (redo) record
                    body: 
                      application/json:
                        schema: records
                        example: |
                          {
                           "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                           "alias":false,
                           "answers":
                             [{
                               "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                               "algorithm":5,
                               "at":"60",
                               "data":null,
                               "expire":"1M",
                               "flags":null,
                               "ip":null,
                               "keyTag":null,
                               "labels":3,
                               "minimum":"1M",
                               "mname":"ns01.moyd.co.",
                               "originalTTL":null,
                               "port":80,
                               "priority":10,
                               "protocol":null,
                               "publicKey":null,
                               "refresh":"1M",
                               "retry":"1M",
                               "rname":"domains@moyd.co",
                               "serial":1409220000,
                               "signature":null,
                               "signatureExpiration":null,
                               "signatureInception":null,
                               "signerName":null,
                               "typeCovered":1,
                               "weight\":1}],
                             "check_id":null,
                             "created_at":"2014-09-22T15:43:47.846Z",
                             "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                             "enabled":true,
                             "name":"www",
                             "operational":true,
                             "primary":true,
                             "region_id":null,
                             "routing_policy":"SIMPLE",
                             "set_id":null,
                             "trashed":false,
                             "ttl":60,
                             "type":"SOA",
                             "updated_at":"2014-09-22T15:43:47.846Z",
                             "version":0,
                             "weight\":1
                          }
                  404:
                    description: Error
            /trash:
              put:
                description: trash a record
                responses:
                  200:
                    description: a json with the trashed record
                    body: 
                      application/json:
                        schema: records
                        example: |
                          {
                           "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                           "alias":false,
                           "answers":
                             [{
                               "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                               "algorithm":5,
                               "at":"60",
                               "data":null,
                               "expire":"1M",
                               "flags":null,
                               "ip":null,
                               "keyTag":null,
                               "labels":3,
                               "minimum":"1M",
                               "mname":"ns01.moyd.co.",
                               "originalTTL":null,
                               "port":80,
                               "priority":10,
                               "protocol":null,
                               "publicKey":null,
                               "refresh":"1M",
                               "retry":"1M",
                               "rname":"domains@moyd.co",
                               "serial":1409220000,
                               "signature":null,
                               "signatureExpiration":null,
                               "signatureInception":null,
                               "signerName":null,
                               "typeCovered":1,
                               "weight\":1}],
                             "check_id":null,
                             "created_at":"2014-09-22T15:43:47.846Z",
                             "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                             "enabled":true,
                             "name":"www",
                             "operational":true,
                             "primary":true,
                             "region_id":null,
                             "routing_policy":"SIMPLE",
                             "set_id":null,
                             "trashed":false,
                             "ttl":60,
                             "type":"SOA",
                             "updated_at":"2014-09-22T15:43:47.846Z",
                             "version":0,
                             "weight\":1
                          }
                  404:
                    description: Error
            /untrash:
              put:
                description: untrash a record
                responses:
                  200:
                    description: a json with the untrashed record
                    body: 
                      application/json:
                        schema: records
                        example: |
                          {
                           "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                           "alias":false,
                           "answers":
                             [{
                               "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                               "algorithm":5,
                               "at":"60",
                               "data":null,
                               "expire":"1M",
                               "flags":null,
                               "ip":null,
                               "keyTag":null,
                               "labels":3,
                               "minimum":"1M",
                               "mname":"ns01.moyd.co.",
                               "originalTTL":null,
                               "port":80,
                               "priority":10,
                               "protocol":null,
                               "publicKey":null,
                               "refresh":"1M",
                               "retry":"1M",
                               "rname":"domains@moyd.co",
                               "serial":1409220000,
                               "signature":null,
                               "signatureExpiration":null,
                               "signatureInception":null,
                               "signerName":null,
                               "typeCovered":1,
                               "weight\":1}],
                             "check_id":null,
                             "created_at":"2014-09-22T15:43:47.846Z",
                             "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                             "enabled":true,
                             "name":"www",
                             "operational":true,
                             "primary":true,
                             "region_id":null,
                             "routing_policy":"SIMPLE",
                             "set_id":null,
                             "trashed":false,
                             "ttl":60,
                             "type":"SOA",
                             "updated_at":"2014-09-22T15:43:47.846Z",
                             "version":0,
                             "weight\":1
                          }
                  404:
                    description: Error
            /undo:
              put:
                description: undo to last record version
                responses:
                  200:
                    description: a json with the reverted record
                    body: 
                      application/json:
                        schema: records
                        example: |
                          {
                           "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                           "alias":false,
                           "answers":
                             [{
                               "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                               "algorithm":5,
                               "at":"60",
                               "data":null,
                               "expire":"1M",
                               "flags":null,
                               "ip":null,
                               "keyTag":null,
                               "labels":3,
                               "minimum":"1M",
                               "mname":"ns01.moyd.co.",
                               "originalTTL":null,
                               "port":80,
                               "priority":10,
                               "protocol":null,
                               "publicKey":null,
                               "refresh":"1M",
                               "retry":"1M",
                               "rname":"domains@moyd.co",
                               "serial":1409220000,
                               "signature":null,
                               "signatureExpiration":null,
                               "signatureInception":null,
                               "signerName":null,
                               "typeCovered":1,
                               "weight\":1}],
                             "check_id":null,
                             "created_at":"2014-09-22T15:43:47.846Z",
                             "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                             "enabled":true,
                             "name":"www",
                             "operational":true,
                             "primary":true,
                             "region_id":null,
                             "routing_policy":"SIMPLE",
                             "set_id":null,
                             "trashed":false,
                             "ttl":60,
                             "type":"SOA",
                             "updated_at":"2014-09-22T15:43:47.846Z",
                             "version":0,
                             "weight\":1
                          }
                  404:
                    description: Error
            get:
              description: Get a record
              responses:
                200:
                  description: a json with the added records
                  body: 
                    application/json:
                      schema: records
                      example: |
                        {
                         "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                         "alias":false,
                         "answers":
                           [{
                             "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                             "algorithm":5,
                             "at":"60",
                             "data":null,
                             "expire":"1M",
                             "flags":null,
                             "ip":null,
                             "keyTag":null,
                             "labels":3,
                             "minimum":"1M",
                             "mname":"ns01.moyd.co.",
                             "originalTTL":null,
                             "port":80,
                             "priority":10,
                             "protocol":null,
                             "publicKey":null,
                             "refresh":"1M",
                             "retry":"1M",
                             "rname":"domains@moyd.co",
                             "serial":1409220000,
                             "signature":null,
                             "signatureExpiration":null,
                             "signatureInception":null,
                             "signerName":null,
                             "typeCovered":1,
                             "weight\":1}],
                           "check_id":null,
                           "created_at":"2014-09-22T15:43:47.846Z",
                           "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                           "enabled":true,
                           "name":"www",
                           "operational":true,
                           "primary":true,
                           "region_id":null,
                           "routing_policy":"SIMPLE",
                           "set_id":null,
                           "trashed":false,
                           "ttl":60,
                           "type":"SOA",
                           "updated_at":"2014-09-22T15:43:47.846Z",
                           "version":0,
                           "weight\":1
                        }
                404:
                  description: Error
            put:
              description: Update a record
              queryParameters:
                record:
                  description: A json with all details
                  example: |
                   {
                     "alias":false,
                     "answer_attributes":
                       [{
                         "algorithm":5,
                         "at":"60",
                         "data":null,
                         "expire":"1M",
                         "flags":null,
                         "ip":null,
                         "keyTag":null,
                         "labels":3,
                         "minimum":"1M",
                         "mname":"ns01.moyd.co.",
                         "originalTTL":null,
                         "port":80,
                         "priority":10,
                         "protocol":null,
                         "publicKey":null,
                         "refresh":"1M",
                         "retry":"1M",
                         "rname":"domains@moyd.co",
                         "signature":null,
                         "signatureExpiration":null,
                         "signatureInception":null,
                         "signerName":null,
                         "typeCovered":1,
                         "weight\":1}],
                       "enabled":true,
                       "name":"www",
                       "primary":true,
                       "routing_policy":"SIMPLE",
                       "set_id":null,
                       "ttl":60,
                       "type":"SOA",
                       "weight":1
                    }
              responses:
                200:
                  description: a json with the updated records
                  body: 
                    application/json:
                      schema: records
                      example: |
                        {
                         "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                         "alias":false,
                         "answers":
                           [{
                             "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                             "algorithm":5,
                             "at":"60",
                             "data":null,
                             "expire":"1M",
                             "flags":null,
                             "ip":null,
                             "keyTag":null,
                             "labels":3,
                             "minimum":"1M",
                             "mname":"ns01.moyd.co.",
                             "originalTTL":null,
                             "port":80,
                             "priority":10,
                             "protocol":null,
                             "publicKey":null,
                             "refresh":"1M",
                             "retry":"1M",
                             "rname":"domains@moyd.co",
                             "serial":1409220000,
                             "signature":null,
                             "signatureExpiration":null,
                             "signatureInception":null,
                             "signerName":null,
                             "typeCovered":1,
                             "weight\":1}],
                           "check_id":null,
                           "created_at":"2014-09-22T15:43:47.846Z",
                           "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                           "enabled":true,
                           "name":"www",
                           "operational":true,
                           "primary":true,
                           "region_id":null,
                           "routing_policy":"SIMPLE",
                           "set_id":null,
                           "trashed":false,
                           "ttl":60,
                           "type":"SOA",
                           "updated_at":"2014-09-22T15:43:47.846Z",
                           "version":0,
                           "weight\":1
                        }
                404:
                  description: Error
            delete:
              description: Delete a record
              responses:
                200:
                  description: a json with the deleted records
                  body: 
                    application/json:
                      schema: records
                      example: |
                        {
                         "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                         "alias":false,
                         "answers":
                           [{
                             "_id":{"$oid":"ffe6eba40000315f33abb8cd"},
                             "algorithm":5,
                             "at":"60",
                             "data":null,
                             "expire":"1M",
                             "flags":null,
                             "ip":null,
                             "keyTag":null,
                             "labels":3,
                             "minimum":"1M",
                             "mname":"ns01.moyd.co.",
                             "originalTTL":null,
                             "port":80,
                             "priority":10,
                             "protocol":null,
                             "publicKey":null,
                             "refresh":"1M",
                             "retry":"1M",
                             "rname":"domains@moyd.co",
                             "serial":1409220000,
                             "signature":null,
                             "signatureExpiration":null,
                             "signatureInception":null,
                             "signerName":null,
                             "typeCovered":1,
                             "weight\":1}],
                           "check_id":null,
                           "created_at":"2014-09-22T15:43:47.846Z",
                           "domain_id":{"$oid":"ffe6eba30000315f33abb8cb"},
                           "enabled":true,
                           "name":"www",
                           "operational":true,
                           "primary":true,
                           "region_id":null,
                           "routing_policy":"SIMPLE",
                           "set_id":null,
                           "trashed":false,
                           "ttl":60,
                           "type":"SOA",
                           "updated_at":"2014-09-22T15:43:47.846Z",
                           "version":0,
                           "weight\":1
                        }
                404:
                  description: Error   
      /{id}:
        /daily_stat:
          get:
            description: Show daily detail domain queries
            queryParameters:
              day:
                description: Day
                example: 31
              month:
                description: Month
                example: 09
              year:
                description: Year
                example: 2014
            responses:
                200:
                  description: a json with the record queries detail
                  body: 
                    application/json:
                      example: |
                        [
                          {"_id":{"$oid":"0000002d00005df76c6d5230"},
                          "count":10,
                          "created_at":"2014-08-22T23:15:18.775Z",
                          "domain_id":{"$oid":"0003927c00005cff2949b760"},
                          "region_id\":{"$oid":"ffedca8c0000eff666eeb35d"},
                          "serverID":"01",
                          "updated_at":"2014-08-22T22:15:18.775Z"
                          },
                          {"_id":{"$oid":"0000002d00005df76c6d5231"},
                          "count":21,
                          "created_at":"2014-08-22T23:15:18.775Z",
                          "domain_id":{"$oid":"0003927c00005cff2949b760"},
                          "region_id\":{"$oid":"ffedca8c0000eff666eeb35d"},
                          "serverID":"01",
                          "updated_at":"2014-08-22T23:15:18.775Z"
                          }
                        ]
                404:
                  description: Error   
        /monthly_total:
          get:
            description: Show monthly total domain queries
            queryParameters:
              month:
                description: Month
                example: 09
              year:
                description: Year
                example: 2014
            responses:
                200:
                  description: a json with the monthly total stats
                  body: 
                    application/json:
                      example: |
                        {
                          "_id":{"$oid":"fff1d6a80000e6f13831ff1a"},
                          "count":12340,
                          "domain_id":{"$oid":"0003927c00005cff2949b760"},
                          "month":10,
                          "year":2014
                        }
                404:
                  description: Error  
        get:
          description: Show domain details
          responses:
            200:
              description: a json with the domains
              body: 
                application/json:
                  schema: domain
                  example: |
                   {
                      "_id":{"$oid":"ffedb9140000eff666eeb352"},
                      "admin_enabled":true,
                      "created_at":null,
                      "last_bill":"2014-10-30",
                      "updated_a\":null,
                      "user_id":{"$oid":"ffedb8900000eff666eeb350"},
                      "zone":"moyd.local"
                    }  
        put:
          description: Update domain details 
          queryParameters:
            domain:
              description: A JSON with domain details
              example: |
                {
                  "zone":"moyd.local",
                  "ttl":60
                }
          responses:
            200:
              description: a json with the domains
              body: 
                application/json:
                  schema: domain
                  example: |
                   {
                      "_id":{"$oid":"ffedb9140000eff666eeb352"},
                      "admin_enabled":true,
                      "created_at":null,
                      "last_bill":"2014-10-30",
                      "updated_a\":null,
                      "user_id":{"$oid":"ffedb8900000eff666eeb350"},
                      "zone":"moyd.local"
                    }
        delete:
          description: Delete a domain
          responses:
            200:
              description: a json with the deleted domains
              body: 
                application/json:
                  schema: domain
                  example: |
                   {
                      "_id":{"$oid":"ffedb9140000eff666eeb352"},
                      "admin_enabled":true,
                      "created_at":null,
                      "last_bill":"2014-10-30",
                      "updated_a\":null,
                      "user_id":{"$oid":"ffedb8900000eff666eeb350"},
                      "zone":"moyd.local"
                    }
      get:
        description: Return all user's domains
        responses:
          200:
            description: a json with the domains
            body: 
              application/json:
                schema: domain
                example: |
                  [
                    {
                    "_id":{"$oid":"ffedb9140000eff666eeb352"},
                    "admin_enabled":true,
                    "created_at":null,
                    "last_bill":"2014-10-30",
                    "updated_a\":null,
                    "user_id":{"$oid":"ffedb8900000eff666eeb350"},
                    "zone":"moyd.local"
                    }
                  ]
          404:
            description: Error 
      post:
        description: Add a domain
        queryParameters:
          domain:
            description: A JSON with domain details
            example: |
              {
                "zone":"moyd.local",
                "ttl":60
              }
        responses:
          200:
            description: a json with the domains
            body: 
              application/json:
                schema: domain
                example: |
                 {
                    "_id":{"$oid":"ffedb9140000eff666eeb352"},
                    "admin_enabled":true,
                    "created_at":null,
                    "last_bill":"2014-10-30",
                    "updated_a\":null,
                    "user_id":{"$oid":"ffedb8900000eff666eeb350"},
                    "zone":"moyd.local"
                  } 
  get:
    description: Show User ID of current user
    responses:
      200:
        description: an user ID
        body: 
          application/json:
            example: 2121ab1212121986fe23
  /{id}:
    get:
      description: Show User ID of current user
      responses:
        200:
          description: a json with user details
          body: 
            application/json:
              schema: user
              example: |
                {
                  "_id":{"$oid":"000ab90d0000f2b7219ea5d7"},
                  "_slugs":["000ab7ee0000badfcf8d085d-oauth2"],
                  "admin":false,
                  "created_at":\"2014-07-12T09:23:59.597Z",
                  "email":null,
                  "notify_by_email":false,
                  "notify_by_sms":false,
                  "sms":null,
                  "updated_at":"2014-07-12T09:23:59.597Z",
                  "user_reference":"000ab7ee0000badfcf8d085d-oauth2"
                }
    delete:
      description: Delete an user
      responses:
        200:
          description: a json with deleted user details
          body: 
            application/json:
              schema: user
              example: |
                {
                  "_id":{"$oid":"000ab90d0000f2b7219ea5d7"},
                  "_slugs":["000ab7ee0000badfcf8d085d-oauth2"],
                  "admin":false,
                  "created_at":\"2014-07-12T09:23:59.597Z",
                  "email":null,
                  "notify_by_email":false,
                  "notify_by_sms":false,
                  "sms":null,
                  "updated_at":"2014-07-12T09:23:59.597Z",
                  "user_reference":"000ab7ee0000badfcf8d085d-oauth2"
                }

